edenia/eden-spend-explorer

.env.example
webapp/Dockerfile
webapp/src/language/en.json
webapp/src/language/es.json

feat(webapp): update dockerfile

---

hapi/src/gql/eden-delegates.gql.js
hapi/src/gql/eden-election.gql.js
hapi/src/gql/eden-transaction.gql.js
hapi/src/gql/index.js
hapi/src/services/eden-delegates.service.js
hapi/src/services/eden-election.service.js
hapi/src/services/hyperion/updaters/eosiotoken-transfer.updater.js
hapi/src/services/worker.service.js

- Resolve #44 
1. Run "make run"
2. Go to localhost:9695
3. See a example like this:

chore(hapi):Adapt for election and delegates information #44

---

hapi/src/constants/transaction.constant.js
hapi/src/services/hyperion/index.js
hapi/src/services/hyperion/updaters/eosiotoken-transfer.updater.js
hapi/src/utils/updater.util.js

- Resolve #56 
1. Run project
2. Go to http://localhost:9695
3. Go to Data->eden_transaction
Example working

feat(hapi): Saves and categorizes all transfers #56

---

hapi/src/constants/transaction.constant.js
hapi/src/services/hyperion/updaters/eosiotoken-transfer.updater.js

- Resolve #61
1. Go to main 
2. See changes in files

fix(hapi):Error in main fixed #61

---

webapp/src/hooks/customHooks/useIncomeReportState.js
webapp/src/routes/IncomeReport/IncomeSelect.js

- Resolve #64 
1. Open  webapp folder
2.  Go to src/hooks/customHooks/useIncomeReportState
3.  See the changes

fix(webapp): delete duplicated useEffect

---

.github/workflows/push-dev-environment.yaml

- set correct env vars for chain ID and API endpoint

Update chain api and id

---

hapi/src/gql/eden-election.gql.js
hapi/src/gql/eden-historic-election.gql.js
hapi/src/services/eden-delegates.service.js
hapi/src/services/eden-historic-delegates.service.js
hasura/migrations/default/1662157545683_alter_table_public_eden_historic_election_alter_column_election_round/down.sql
hasura/migrations/default/1662157545683_alter_table_public_eden_historic_election_alter_column_election_round/up.sql
hasura/migrations/default/1662157566016_alter_table_public_eden_election_alter_column_election_round/down.sql
hasura/migrations/default/1662157566016_alter_table_public_eden_election_alter_column_election_round/up.sql
webapp/src/gql/income.gql.js
webapp/src/hooks/customHooks/useIncomeReportState.js
webapp/src/routes/IncomeReport/index.js

- Resolve #77 
1. Run project
2. See on localhost:9695
3. See on eden_election and eden_historic_election

refactor(hasura): change column name

---

hapi/src/services/eden-historic-delegates.service.js
hapi/src/services/hyperion/updaters/genesiseden-withdraw.updater.js
hasura/migrations/default/1662398157336_alter_table_public_eden_transaction_alter_column_txid/down.sql
hasura/migrations/default/1662398157336_alter_table_public_eden_transaction_alter_column_txid/up.sql

- Resolve #82 
1. Run project
2. Open localhost:9695
3. See on eden_transaction category "unclaimed" on income type transaction

feat(hapi): add category on income transaction

---

webapp/src/hooks/customHooks/useIncomeReportState.js
webapp/src/language/en.json
webapp/src/language/es.json
webapp/src/routes/IncomeReport/index.js

- Resolve #80 
2. open localhost:3000 in your browser
3. click on income in the sidebar and see the change
4. There is an example in the image

feat(webapp): show in income view the next disbursement

---

webapp/src/hooks/customHooks/useIncomeReportState.js
webapp/src/routes/IncomeReport/IncomeTable.js
webapp/src/routes/IncomeReport/index.js

- Resolve #83 
- Resolve #84
2. open in your brouser localhost:3000
3. click on income in the sidebar
4. see the the comma in the numbers and round numbers

feat(webapp): thousands separator

---

.github/workflows/push-dev-environment.yaml
.github/workflows/push-prod-environment.yaml

- Resolve #71 
1. Visit [eosreports](https://eosreports.com/)
2. See Eden Treasury Balance

fix(github): changes variables to correct api

---

docker-compose.yaml
hasura/metadata/databases/default/tables/public_eden_delegates.yaml
hasura/metadata/databases/default/tables/public_eden_election.yaml
hasura/metadata/databases/default/tables/public_eden_historic_election.yaml
hasura/metadata/databases/default/tables/public_eden_transaction.yaml

- Resolve #89 
1. go to hasura folder: /eosio-spend-explorer/hasura/metadata/databases/default/tables
2. see modified files by migration: public_eden_delegates.yaml, public_eden_election.yaml, public_eden_historic_election.yaml, public_eden_transaction.yaml.

fix(hasura): set hasura permissions for guest role

---

webapp/src/routes/IncomeReport/IncomeSelect.js

- Resolve #90 
1. Visit [eosreports](eosreports.com)
2. Enter on Income, you should can see this

feat(webapp): hide delegate field #90

---

hasura/metadata/databases/default/tables/public_total_income_by_election.yaml

- Resolve #112 
1. Run the project
2. Go to localhost: 3000
3. Click on income in the sidebar and see that everything is working fine.

fix(hasura): add permissions to guest role

---

hasura/metadata/databases/default/tables/public_historic_incomes.yaml
hasura/metadata/databases/default/tables/public_incomes_claimed_or_unclaimed.yaml
hasura/metadata/databases/default/tables/tables.yaml
hasura/migrations/default/1664213346535_run_sql_migration/down.sql
hasura/migrations/default/1664213346535_run_sql_migration/up.sql
hasura/migrations/default/1664228084282_run_sql_migration/down.sql
hasura/migrations/default/1664228084282_run_sql_migration/up.sql
hasura/migrations/default/1664228175080_drop_view_public_incomes_claimed_or_unclaimed/down.sql
hasura/migrations/default/1664228175080_drop_view_public_incomes_claimed_or_unclaimed/up.sql
hasura/migrations/default/1664228203908_run_sql_migration/down.sql
hasura/migrations/default/1664228203908_run_sql_migration/up.sql
webapp/src/gql/income.gql.js
webapp/src/hooks/customHooks/useIncomeReportState.js
webapp/src/routes/IncomeReport/IncomeChart.js
webapp/src/routes/IncomeReport/IncomePieChart.js

- Resolve #131 
1. Run project
2. Enter to Income and you should see this:

fix(webapp): incomes graphs works fine #131

---

webapp/src/gql/income.gql.js
webapp/src/hooks/customHooks/useIncomeReportState.js
webapp/src/language/en.json
webapp/src/language/es.json
webapp/src/routes/IncomeReport/IncomeChart.js
webapp/src/routes/IncomeReport/IncomeTable.js

- Resolve #128 
1. run the project and open in your browser localhost:3000
2. Click on income on the sidebar
3. Scroll down to the table and see the new features

feat(webapp): add withdrawal date to table

---

hasura/metadata/databases/default/tables/public_percent_by_all_elections.yaml
hasura/metadata/databases/default/tables/public_percent_by_delegades.yaml
hasura/metadata/databases/default/tables/public_percent_by_delegates.yaml
hasura/metadata/databases/default/tables/tables.yaml
hasura/migrations/default/1664322664765_run_sql_migration/down.sql
hasura/migrations/default/1664322664765_run_sql_migration/up.sql
hasura/migrations/default/1664324349407_run_sql_migration/down.sql
hasura/migrations/default/1664324349407_run_sql_migration/up.sql
hasura/migrations/default/1664324578106_rename_view_public_percent_by_delegades/down.sql
hasura/migrations/default/1664324578106_rename_view_public_percent_by_delegades/up.sql
webapp/src/gql/income.gql.js
webapp/src/hooks/customHooks/useIncomeReportState.js
webapp/src/routes/IncomeReport/IncomeTable.js
webapp/src/routes/IncomeReport/index.js

- Resolve #119 
1. Run Project

feat(webapp): add percent un/claimed to table

---

webapp/package.json
webapp/src/routes/IncomeReport/IncomeChart.js
webapp/src/routes/IncomeReport/IncomePieChart.js
webapp/src/routes/IncomeReport/IncomeStackedChart.js
webapp/yarn.lock

- Resolve #101 
1. Run project
2. Enter to Income
3. Click to button
4. Should see this on downloads:

feat(webapp): download graphics

---

webapp/src/language/en.json
webapp/src/language/es.json
webapp/src/routes/IncomeReport/IncomeTable.js
webapp/src/routes/IncomeReport/index.js

- Resolve #155 
1. Run the project and open localhost:3000 in your browser
2. Click on icome in the sidebar
3. Scroll down to tablel and test it.

fix(webapp): fix table error

---

hasura/metadata/databases/default/tables/public_historic_expenses.yaml
hasura/metadata/databases/default/tables/public_percent_by_all_elections_expenses.yaml
hasura/metadata/databases/default/tables/public_percent_by_delegates_expenses.yaml
hasura/metadata/databases/default/tables/public_percent_by_delegates_incomes.yaml
hasura/metadata/databases/default/tables/public_total_by_category.yaml
hasura/metadata/databases/default/tables/public_total_by_category_and_election.yaml
hasura/metadata/databases/default/tables/public_total_by_election.yaml
hasura/metadata/databases/default/tables/public_transaction_by_category_and_election.yaml

- Resolve #158 
1. Run project like guest rol
2. Enter on income and see data like this:

fix(hasura): add permissions to guest rol

---

.github/workflows/codeql-analysis.yml

- Resolve #issueNumber
1. first step
2. next step

feat(github): Add code scanning

---

hapi/src/services/dfuse/updaters/eosiotoken-transfer.updater.js

- Resolve #163
1. Go to hapi/src/services/dfuse/updaters/eosiotoken-transfer.updater.js and see 18 line
- []X I Ran a spell check

refactor(hapi) save all memo

---

kubernetes/postgres-statefulset.yaml
kubernetes/storageclass.yaml
kubernetes/wallet-statefulset.yaml

- Resolve #issueNumber
1. first step
2. next step

ci(k8s): fix storage class name

---

hapi/src/services/dfuse/index.js

- Resolve #issueNumber
1. first step
2. next step

bug(hapi): adding comment

---

hapi/src/gql/eden-delegates.gql.js
hapi/src/services/dfuse/index.js
hapi/src/services/eden-historic-delegates.service.js
hapi/src/utils/updater.util.js
hasura/metadata/databases/default/tables/public_eden_delegates.yaml
hasura/migrations/default/1666133326081_alter_table_public_eden_delegates_add_column_last_synced_at/down.sql
hasura/migrations/default/1666133326081_alter_table_public_eden_delegates_add_column_last_synced_at/up.sql
hasura/migrations/default/1666164783646_alter_table_public_eden_historic_election_alter_column_election/down.sql
hasura/migrations/default/1666164783646_alter_table_public_eden_historic_election_alter_column_election/up.sql
hasura/migrations/default/1666203318207_run_sql_migration/down.sql
hasura/migrations/default/1666203318207_run_sql_migration/up.sql
webapp/src/gql/expense.gql.js
webapp/src/gql/income.gql.js
webapp/src/hooks/customHooks/useExpenseReportState.js
webapp/src/hooks/customHooks/useIncomeReportState.js

- Resolve #181
2. You can see in localhost:3000 that data is loaded faster

fix(hapi): improve dfuse data saving time

---

hapi/src/services/dfuse/index.js

- Resolve #184 
1. Run project
2. Wait 2 hours aprox
3. Enter to localhost:9695

fix(hapi): add validation by name transaction

---

hasura/metadata/databases/default/tables/public_expenses_by_delegate.yaml
hasura/metadata/databases/default/tables/public_incomes_by_delegate.yaml

- Resolve #199 
1. Run Project
2. Enter to General Income and General Expense

fix(hasura): add guest role permiss

---

webapp/src/language/en.json
webapp/src/language/es.json
webapp/src/routes/About/index.js
webapp/src/routes/About/styles.js

- Resolve #208 
2. click on about in the sidebar and see the new features

feat(webapp): improve about view

---

webapp/src/components/AuthButton/index.js
webapp/src/components/AuthButton/styles.js
webapp/src/components/Header/index.js
webapp/src/components/Sidebar/index.js
webapp/src/components/Sidebar/styles.js
webapp/src/layouts/Dashboard/index.js

fea(components): moved login/logout components to sidebar

---

webapp/src/components/PieChartReport/index.js
webapp/src/components/PieChartReport/styles.js
webapp/src/hooks/customHooks/useExpenseReportState.js
webapp/src/hooks/customHooks/useIncomeReportState.js
webapp/src/hooks/customHooks/useTresuryBalanceState.js
webapp/src/language/en.json
webapp/src/language/es.json
webapp/src/routes/ExpenseReport/index.js
webapp/src/routes/ExpenseReport/styles.js
webapp/src/routes/IncomeReport/index.js
webapp/src/utils/new-format-objects.js

- Resolve #217
- Resolve #221 
1. Run Project
2. In the view Expense you can see this:

feat(webapp): update piechart view

---

webapp/src/components/TableReport/index.js

- Resolve #220 
1. run the project and open it in your browser localhost:3000
2. click on spend tool if you are a delegate
3. See the transactions table doesn't have repeat transactions

fix(webapp): information table

---

hapi/src/gql/eden-transaction.gql.js
hapi/src/services/dfuse/index.js
hapi/src/services/dfuse/updaters/edenexplorer-categorize.updater.js
hapi/src/services/dfuse/updaters/index.js

- Resolve #226
2. this is a backend change

feat(backend): listen categorize action in backend

---

webapp/src/gql/income.gql.js

- Resolve #235 
1. Run project
2. Enter to income and see the bar chart

fix(webapp): bug fixed

---

webapp/src/gql/expense.gql.js
webapp/src/hooks/customHooks/useSpendToolsState.js

- Resolve #234
1. run the project and open the local host
2. when a delegate updates transactions, it is going to be updated in real-time

feat(webapp): modify the memo transaction in frontend

---

webapp/src/hooks/customHooks/useSpendToolsState.js
webapp/src/routes/SpendTools/styles.js

- Resolve #238 
1. run the project and open localhost:3000
2. you can open the spending tool and see your changes in real time.

feat(webapp): update list transaction information

---

webapp/src/language/en.json
webapp/src/language/es.json
webapp/src/routes/ExpenseReport/index.js
webapp/src/routes/IncomeReport/index.js
webapp/src/utils/new-format-objects.js

- Resolve #240 
1. run the project in localhost:3000
2. go to income and expense and see the table

content(webapp): redundant data in table

---

webapp/src/components/BarChartReport/index.js
webapp/src/components/BarChartReport/styles.js
webapp/src/components/DelegateDetails/index.js
webapp/src/components/DelegateDetails/styles.js
webapp/src/components/PieChartReport/index.js
webapp/src/components/PieChartReport/styles.js
webapp/src/components/Select/index.js
webapp/src/components/StackedBarChartReport/index.js
webapp/src/components/StackedBarChartReport/styles.js
webapp/src/routes/DelegateReport/index.js
webapp/src/routes/DelegateReport/styles.js
webapp/src/routes/ExpenseReport/index.js
webapp/src/routes/ExpenseReport/styles.js
webapp/src/routes/IncomeReport/index.js
webapp/src/routes/IncomeReport/styles.js
webapp/src/routes/SpendTools/styles.js
webapp/src/theme/palette.js

- Resolve #247 
1. Run the project and open localhost:3000
2. see the improved styles

style(webapp): styles refactor

---

webapp/src/layouts/Dashboard/index.js

- Resolve #250 
1. Run the project and open localhost:3000 in your browser
2. Scroll down in any view and open another view, you will be able to see the  new view from the top

fix(webapp): loading scroll

---

webapp/src/utils/new-format-objects.js

- Resolve #256 
1. Run Project
2. Enter to Delegate
3. Must see someting like this:
Before:
Now:

fix(webapp): add substract to uncategorized

---

hasura/metadata/actions.yaml

- Resolve #268 
1. Run Project
2. Enter to Expense, Income or Delegate

fix(hasura): add permisions guest

---

.github/workflows/push-dev-environment.yaml
.github/workflows/push-prod-environment.yaml

fix(devops): change versions for deprecated issues

fix(devops): change versions for deprecated issues

---

hapi/src/gql/income-frontend.gql.js
hapi/src/gql/index.js
hapi/src/routes/get-income.route.js
hapi/src/routes/index.js
hapi/src/services/income-frontend.service.js
hapi/src/services/index.js
hasura/metadata/actions.graphql
hasura/metadata/actions.yaml
webapp/src/gql/income.gql.js
webapp/src/hooks/customHooks/useIncomeReportState.js
webapp/src/utils/new-format-objects.js

- Resolve #272 
1. Run Project
2. Enter to income and use it

refactor(webapp, hapi): make queries of frontend from backend

---

webapp/src/routes/ExpenseReport/index.js
webapp/src/routes/IncomeReport/index.js

- Resolve #266 
1. Run project
2. Enter to Income or Expense
3. Select One Election and Scroll Down to table
4. Click a delegate name

feat(webapp): use EOSDetective instead of EOSAuthority

---

docker-compose.yaml
hasura/Dockerfile

- Resolve #issueNumber
1. first step
2. next step

fix(hasura): update hasura version

---

webapp/src/hooks/customHooks/useSpendToolsState.js
webapp/src/routes/SpendTools/index.js

- Resolve #301 
1. Run Project
2. Log in
3. Enter to Spend Tools
4. Look available founds

feat(webapp): get balance from blockchain

---

webapp/src/components/TreasuryBalance/styles.js

- Resolve #299
1. Run Project
2. Enter to Income or Expense
3. Must see someting like this:

feat(webapp): change min width

---

docker-compose.yaml
hapi/yarn.lock
hasura/metadata/databases/default/tables/public_eden_transaction.yaml
hasura/migrations/default/1670610149638_alter_table_public_eden_transaction_add_column_memo/down.sql
hasura/migrations/default/1670610149638_alter_table_public_eden_transaction_add_column_memo/up.sql

- Resolve #311 
1. delete de DB again

fix(hapi): memo migration

---

hapi/src/gql/income-frontend.gql.js
hapi/src/services/income-frontend.service.js
webapp/src/components/BarChartReport/index.js
webapp/src/gql/expense.gql.js
webapp/src/hooks/customHooks/useExpenseReportState.js
webapp/src/utils/new-format-objects.js

- Resolve #302
1. Run Project
2. Enter to Income or Expense
3. Position pointer hover a election, must see this:

feat(webapp, hapi): add election date to bar chart

---

webapp/src/components/Select/index.js
webapp/src/components/Sidebar/index.js
webapp/src/routes/ExpenseReport/index.js
webapp/src/routes/IncomeReport/index.js
webapp/src/utils/new-format-objects.js

- Resolve #314
2. go to delegate and see the expense chart on a right way

fix(webapp): delegate chart expenses

---

webapp/src/components/Sidebar/styles.js
webapp/src/layouts/Dashboard/styles.js

- Resolve #308 
1. Run Project
2. Must see this:

fix(webapp): changes margin sidebar

---

webapp/src/constants/footer.js

- Resolve #296 
1. Run Project
2. Must see this:

feat(webapp): add report a bug

---

hapi/src/services/dfuse/index.js
hapi/src/services/dfuse/updaters/eosiotoken-transfer.updater.js
hasura/metadata/databases/default/tables/public_eden_transaction.yaml
webapp/src/components/TableReport/index.js
webapp/src/components/TreasuryBalance/index.js
webapp/src/gql/expense.gql.js
webapp/src/gql/general.gql.js
webapp/src/gql/spendTools.gql.js
webapp/src/hooks/customHooks/useSpendToolsState.js
webapp/src/hooks/customHooks/useTresuryBalanceState.js
webapp/src/routes/ExpenseReport/styles.js
webapp/src/routes/IncomeReport/styles.js
webapp/src/routes/SpendTools/index.js
webapp/src/routes/SpendTools/styles.js

- Resolve #320 
1. Run the project and open localhost:3000 in your browser
2. Click on spendTool in the sidebar, you will be able to see all your transactions and edit transactions, and see changes in real-time

fix(webapp): improving user experience

---

webapp/src/layouts/Dashboard/index.js

- Resolve #321
1. run the project and open localhost:3000
2. see all pages have a right margin

fix(webapp): review margin between sidebar and main content

---

webapp/package.json
webapp/src/components/Sidebar/index.js
webapp/src/components/Sidebar/styles.js
webapp/yarn.lock

- Resolve #306 
2. Click on the image logo to go to the home view

feat(webapp): add interactions to the main logo

---

.github/workflows/push-dev-environment.yaml
.github/workflows/push-prod-environment.yaml

- Resolve #333 
1. You can recategorize an old transaction without delay

fix(webapp): add ual api to yaml file

---

.github/workflows/push-dev-environment.yaml
.github/workflows/push-prod-environment.yaml
makefile
utils/meta.mk

Fix actions dev pdn

---

kubernetes/ingress.yaml

Fix(devops): change on ingress for use crtResolver

Fix(devops): change on ingress for use crtResolver

---

makefile

fix(devops): delete tls configuration makefile

fix(devops): delete tls configuration makefile

---

.github/workflows/push-dev-environment.yaml

fix(devops): change dns for webapp and hasura

fix(devops): change dns for webapp and hasura

---

.github/workflows/push-prod-environment.yaml

remove pre release flag from releases

ci(release): Remove pre-release flag

---

hapi/src/services/dfuse/index.js
hapi/src/services/eden-delegates.service.js
hapi/src/services/eden-historic-delegates.service.js
makefile
webapp/src/hooks/customHooks/useDelegateReportState.js

- Resolve #348
1. run the project and check if exist a new error

fix(hapi): dfuse on dev error

---

.github/workflows/push-dev-environment.yaml

fix(hasura): change endpoint for dev

fix(hasura): change endpoint for dev

---

hapi/src/services/dfuse/index.js
webapp/src/hooks/customHooks/useSpendToolsState.js
webapp/src/routes/IncomeReport/index.js
webapp/src/utils/new-format-objects.js

- Resolve #353 
1. run the project and send tokens to test it.

fix(webapp): verify if is delegate

---

webapp/src/hooks/customHooks/useDelegateReportState.js
webapp/src/utils/new-format-objects.js

- Resolve #365 
2.  click on delegate and see the charts in a correct way

fix(webapp): show uncategorized in delegate view by piechart

---

hapi/src/services/dfuse/index.js
hapi/src/services/dfuse/updaters/edenexplorer-categorize.updater.js
hapi/src/services/dfuse/updaters/eosiotoken-transfer.updater.js
hapi/src/services/dfuse/updaters/genesiseden-fundtransfer.updater.js
hapi/src/utils/updater.util.js

- Resolve #362 
2. when a delegate withdraws money you would be able to see that information in realtime in the correct way

fix(hapi): fix save fundtransfer in real time

---

.github/workflows/push-dev-environment.yaml

clean data bd new value .env

---

webapp/src/utils/new-format-objects.js

- Resolve #371 
2. see delegate view has correct data in its charts

fix(webapp) fix stakedBar data

---

webapp/src/utils/new-format-objects.js

- Resolve #364 
1. Run Project
2. Enter to expense

fix(webapp): changes data format on expense

---

hapi/src/services/dfuse/updaters/edenexplorer-categorize.updater.js
hapi/src/utils/updater.util.js
webapp/src/App.js
webapp/src/gql/general.gql.js
webapp/src/gql/spendTools.gql.js
webapp/src/hooks/customHooks/useSpendToolsState.js
webapp/src/hooks/customHooks/useTresuryBalanceState.js
webapp/src/routes/SpendTools/index.js
webapp/src/utils/new-format-objects.js

- Resolve #374 
2. create transactions and categorize transactions

feat(webapp): save the most recent idElection spend tool view

---

webapp/src/components/TableReport/index.js

- Resolve #303 
1. Run Project
2. Enter to Income, Spend tools or expense
3. Try export table to pdf or cvs

feat(webapp): add export buttom

---

webapp/src/gql/general.gql.js
webapp/src/hooks/customHooks/useDelegateReportState.js
webapp/src/hooks/customHooks/useExpenseReportState.js
webapp/src/hooks/customHooks/useIncomeReportState.js
webapp/src/routes/ExpenseReport/index.js
webapp/src/routes/IncomeReport/index.js

- Resolve #376 
1. run the project and test whole the system, we can't see changes

refactor(webapp): delete unused code

---

webapp/package.json
webapp/src/components/AuthButton/index.js
webapp/src/components/Sidebar/index.js
webapp/src/context/state.context.js
webapp/src/hooks/useUAL/index.js
webapp/src/index.js
webapp/yarn.lock

- Resolve #123 
1. run `make run`
2. go to `localhost:3000`
3. test the login button

feat(webapp): integrate ual hook

---

webapp/src/routes/Help/index.js
webapp/src/routes/Help/styles.js

- Resolve #383 
2. go to the help section and see the images with the correct dimensions

fix(webapp):bad images dimentions on mobile version in help section

---

webapp/src/gql/eden-expense.gql.js

- Resolve #387 
1. first step
2. next step

fix(webapp): add order to request query

---

webapp/src/components/LineChartReport/index.js
webapp/src/hooks/customHooks/useIncomeReportState.js
webapp/src/utils/new-format-objects.js

- Resolve #390 
1. Run Project
2. Enter to Income, must see this:

fix(webapp): show data by date and add filter

---

webapp/src/language/en.json

Update homepage texts

---

webapp/src/hooks/customHooks/useSpendToolsState.js

- Resolve #393 
1. Run Project
2. Enter to Spend Tools 
3. Try recategorized transactions

fix(webapp): add missing validation

---

contract/edenexplorer/include/edenexplorer.hpp
contract/edenexplorer/src/edenexplorer.cpp
contract/edenexplorer/tests/tests.cpp
hapi/src/gql/eden-transaction.gql.js
hapi/src/services/dfuse/index.js
hapi/src/services/dfuse/updaters/edenexplorer-categorize.updater.js
hapi/src/services/dfuse/updaters/eosiotoken-transfer.updater.js
hapi/src/services/dfuse/updaters/genesiseden-fundtransfer.updater.js
hapi/src/utils/dfuse.util.js
hasura/metadata/databases/default/tables/public_eden_transaction.yaml
hasura/migrations/default/1673556739883_alter_table_public_eden_transaction_add_column_digest/down.sql
hasura/migrations/default/1673556739883_alter_table_public_eden_transaction_add_column_digest/up.sql
hasura/migrations/default/1673565665020_alter_table_public_eden_transaction_drop_column_memo/down.sql
hasura/migrations/default/1673565665020_alter_table_public_eden_transaction_drop_column_memo/up.sql
webapp/src/gql/eden-expense.gql.js
webapp/src/hooks/customHooks/useSpendToolsState.js
webapp/src/language/en.json
webapp/src/language/es.json
webapp/src/routes/SpendTools/index.js
webapp/src/routes/SpendTools/spendTool-table-report.js
webapp/src/routes/SpendTools/styles.js
webapp/src/routes/index.js

- Resolve #396 
1.  Run the project and try to categorize something

fix(webapp): check the number Txs

---

webapp/src/routes/SpendTools/index.js

fix(webapp): add missing variable

---

hapi/src/services/dfuse/updaters/eosiotoken-transfer.updater.js
webapp/src/hooks/customHooks/useSpendToolsState.js
webapp/src/routes/SpendTools/index.js

- Resolve #409 
1. run the project and try to categorize a transaction

fix(webapp): fix recategorize error

---

.github/workflows/push-dev-environment.yaml

Delete postgres Database for begin again

Delete postgres Database for begin again

---

webapp/src/language/es.json

- Resolve #414 
1. run the project and open localhost:3000 in your browser.
2. go to income view and see the text in both languages, English, and Spanish.

feat(webapp): translate next distribution text

---

webapp/src/components/LineChartReport/custom-lineChart.js
webapp/src/components/LineChartReport/index.js
webapp/src/components/LineChartReport/styles.js
webapp/src/components/Sidebar/index.js
webapp/src/hooks/customHooks/useIncomeReportState.js
webapp/src/routes/Home/styles.js
webapp/src/routes/IncomeReport/index.js
webapp/src/utils/new-format-objects.js

- Resolve #420 
2. Go to income view and see the treasury chart and try to see all the information by filters

fix(webapp): improve ui ux treasury balance chart

---

webapp/src/components/BarChartReport/custom-barChart.js
webapp/src/components/LineChartReport/custom-lineChart.js
webapp/src/components/LineChartReport/index.js
webapp/src/components/LineChartReport/styles.js
webapp/src/language/en.json
webapp/src/language/es.json

- Resolve #425
2. You will be able to see the chart on mobile and desktop with a better user experience
-Desktop
-Mobile

fix(webapp): ui ux improvements on treasury chart

---

.github/workflows/push-dev-environment.yaml

Renew db postgres dev

---

.github/workflows/push-dev-environment.yaml

Renew Bd dev

---

hapi/src/services/dfuse/updaters/eosiotoken-transfer.updater.js
hapi/src/services/dfuse/updaters/genesiseden-fundtransfer.updater.js
hapi/src/utils/community.util.js

- Resolve #440 
1. Run the project and call the withdraw action in the Eden contract

fix(hapi): subtract claimed from unclaimed

---

hapi/src/services/dfuse/updaters/edenexplorer-categorize.updater.js
hasura/metadata/databases/default/tables/public_expenses_by_category_election_and_delegate.yaml
hasura/metadata/databases/default/tables/tables.yaml
hasura/migrations/default/1677714380669_run_sql_migration/down.sql
hasura/migrations/default/1677714380669_run_sql_migration/up.sql
hasura/migrations/default/1677714387991_run_sql_migration/down.sql
hasura/migrations/default/1677714387991_run_sql_migration/up.sql
hasura/migrations/default/1677733616588_run_sql_migration/down.sql
hasura/migrations/default/1677733616588_run_sql_migration/up.sql
webapp/src/gql/eden-expense.gql.js
webapp/src/hooks/customHooks/useDelegateReportState.js
webapp/src/utils/new-format-objects.js

- Resolve #442 
1. Run the project
2. Go to delegate view and y expense view and verify if the expenses are ok

fix(webapp): expenses by category

---

hapi/src/services/dfuse/updaters/edenexplorer-categorize.updater.js
hapi/src/services/dfuse/updaters/eosiotoken-transfer.updater.js

- Resolve #444 
1. Run the project
2. Recategorized and validate it is not repeat

fix(hapi): validate categorized transaction

---

kubernetes/postgres-statefulset.yaml

fix(postgres): upgrade posgres version

fix(postgres): upgrade posgres version

---

docker-compose.yaml

fix(postgres): upgrade posgres version docker compose

fix(postgres): upgrade posgres version docker compose

---

kubernetes/hapi-deployment.yaml
kubernetes/hasura-deployment.yaml
kubernetes/postgres-statefulset.yaml
kubernetes/webapp-deployment.yaml

fix(devops): change limits resources kubernetes

fix(devops): change limits resources kubernetes

---

kubernetes/hapi-deployment.yaml
kubernetes/hasura-deployment.yaml
kubernetes/webapp-deployment.yaml

fix(devops): change cpu requests pdn

fix(devops): change cpu requests pdn
